### ISSUE TITLE
can end up in some "non software reset recoverable" state?

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/Qwiic_Power_Switch_Library#1]
I am using the qwiic power switch in a design that is deployed in remote regions. We have some prototypes in the Arctic, we are very happy with these, all seems to work well on the field :) .

However, doing some "stress tests" in the lab, I think I may have found a situation where there is a way to put the Qwiic switch in a "non software reset recoverable" state, which is a bit scary.

The situation was:

- I had a Qwiic power switch working with an Artemis board
- there was data going "through" the qwiic power switch, when I decided to re-upload code on the artemis
- the code uploaded fine
- but then at reboot the qwiic switch could not be discovered
- I pressed the software reset button of my AGT, but still no qwiic power switch discovered
- I had in the end to switch off the power (disconnect the USB from the computer) and then at re-power the qwiic was discovered

I will try to find time to investigate more on this and see if I can get a reliable test case. That kind of situation should not happen in practice, but still, a bit scary.

Any more people with similar experience?

**Comment by PaulZC** [comment]
Hi JR,
The Qwiic Power Switch contains no programmable parts, it uses two non-configurable parts from TI.
Best guess, you managed to confuse whatever was hanging on the far side of the switch such that it pulled the bus into an illegal state (clock and/or data line pulled permanently low).
Please let us know what you find.
Best wishes,
Paul

**Comment by jerabaul29** [comment]
Aaah, thank you, this is very interesting to hear :) .

I will try to understand more of what happens and let you know :) .

**Comment by PaulZC** [comment]
Hi JR (@jerabaul29 ),

I suspect this issue has gone stale? I'm going to close it, but please re-open if you need more help with this.

Best wishes,
Paul

**Comment by jerabaul29** [comment]
Yes, sorry, I had no time to investigate. I can reproduce the problem: when resetting the MCU while operating with the qwiic switch, sometimes the qwiic switch hangs and I cannot reconnect to it even after resetting the MCU again - I need a full power cycling. Guess this is because the reset happens while some form of transmission is happening, but no idea how to progress further investigating the issue, and little time these days.

**Comment by PaulZC** [comment]
Hi JR (@jerabaul29 ),

Apologies. It has been a while!

After all these years, I finally understand this issue.

In ```powerOff```, I was turning the power off via GPIO0 and the FET. And then an instant later, attempting to isolate the I2C bus via GPIO3. This caused I2C corruption as the power was already collapsing during the isolation write. I was able to get the QPS into some very strange states, powered on but isolated, and not-isolated but not powered on either (which drags the bus down)... The solution for ```powerOff``` is to isolate first, wait 10ms, then turn the power off. I've fixed this in v1.0.1. More details are in the release notes:

https://github.com/sparkfun/SparkFun_Qwiic_Power_Switch_Arduino_Library/releases/tag/v1.0.1

Apologies for the inconvenience!

Best wishes,
Paul

**Comment by jerabaul29** [comment]
Thank you very much for the explanation and for pushing a fix - it is amazing to see how well open source works, and that open source gives a long term perspective! :)

Thanks for the fix. In the meantime I had added some delays here and there in the code, and I think that the problem had mostly disappeared. This is consistent with what you explain :) .
