### ISSUE TITLE
Doesn't work with Adafruit BMP390?

### ISSUE THREAD

**Issue by jvoermans** [sparkfun/Qwiic_Power_Switch_Library#2]
I'm trying to turn on/off the Adafruit BMP390 breakout using the power switch. Turning off works fine, but when I try to turn it on again, the microcontroller will hang. I repeated multiple times using Arduino Mega. Other sensors seem to work fine with the switch. Any ideas what the problem may be?

**Comment by PaulZC** [comment]
Hi @jvoermans ,

Curious... It sounds like the power is momentarily glitching or "browning out" when you turn the power switch on?

The BMP390 itself draws very little current. Large capacitors can draw a big gulp of current as they charge up - the "in-rush". Looking at the Adafruit schematic, the board has a couple of 10uF capacitors. I wouldn't call those especially 'large'.

Maybe it has something to do with the 5V to 3.3V voltage regulation and level-shifting circuitry on the Adafruit boards? Have you tried a different Adafruit sensor (with the same voltage regulation and level-shifting circuitry)? Do you see the same thing?

Best wishes,
Paul

**Comment by PaulZC** [comment]
Closing… Please reopen if you need more help with this.

**Comment by PaulZC** [comment]
Hi @jvoermans ,

Apologies for the time this has taken... I believe I have seen the same issue - and have resolved it in version 1.0.1. Please see: https://github.com/sparkfun/SparkFun_Qwiic_Power_Switch_Arduino_Library/issues/1#issuecomment-2437286353

Best wishes,
Paul
